// cli/internal/server/frontend/src/routes/nodes/[nodeId]/projects/[projectId]/beads/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { createClient } from '$lib/gql/client';
	import { gql } from 'graphql-request';

	const BEADS_QUERY = gql`
		query BeadsByProject($projectID: String!, $first: Int, $after: String) {
			beadsByProject(projectID: $projectID, first: $first, after: $after) {
				edges {
					node {
						id
						title
						status
						priority
					}
					cursor
				}
				pageInfo {
					hasNextPage
					endCursor
				}
				totalCount
			}
		}
	`;

	interface BeadNode {
		id: string;
		title: string;
		status: string;
		priority: number;
	}

	interface BeadEdge {
		node: BeadNode;
		cursor: string;
	}

	interface PageInfo {
		hasNextPage: boolean;
		endCursor: string | null;
	}

	interface BeadsResult {
		beadsByProject: {
			edges: BeadEdge[];
			pageInfo: PageInfo;
			totalCount: number;
		};
	}

	let { data }: { data: PageData } = $props();

	let edges = $state<BeadEdge[]>(data.beads.edges);
	let pageInfo = $state<PageInfo>(data.beads.pageInfo);
	let totalCount = $state<number>(data.beads.totalCount);
	let loadingMore = $state(false);

	async function loadMore() {
		if (!pageInfo.hasNextPage || loadingMore) return;
		loadingMore = true;
		try {
			const client = createClient();
			const result = await client.request<BeadsResult>(BEADS_QUERY, {
				projectID: data.projectId,
				first: 10,
				after: pageInfo.endCursor
			});
			edges = [...edges, ...result.beadsByProject.edges];
			pageInfo = result.beadsByProject.pageInfo;
			totalCount = result.beadsByProject.totalCount;
		} finally {
			loadingMore = false;
		}
	}

	function statusClass(status: string): string {
		switch (status) {
			case 'open':
				return 'text-blue-600 dark:text-blue-400';
			case 'in-progress':
				return 'text-yellow-600 dark:text-yellow-400';
			case 'closed':
				return 'text-green-600 dark:text-green-400';
			case 'blocked':
				return 'text-red-600 dark:text-red-400';
			default:
				return 'text-gray-500 dark:text-gray-400';
		}
	}
</script>

<div class="space-y-4">
	<div class="flex items-center justify-between">
		<h1 class="text-xl font-semibold dark:text-white">Beads</h1>
		<span class="text-sm text-gray-500 dark:text-gray-400">
			{edges.length} of {totalCount}
		</span>
	</div>

	<div class="overflow-hidden rounded-lg border border-gray-200 dark:border-gray-700">
		<table class="w-full text-sm">
			<thead>
				<tr class="border-b border-gray-200 bg-gray-50 dark:border-gray-700 dark:bg-gray-800">
					<th class="px-4 py-3 text-left font-medium text-gray-600 dark:text-gray-300">ID</th>
					<th class="px-4 py-3 text-left font-medium text-gray-600 dark:text-gray-300">Title</th>
					<th class="px-4 py-3 text-left font-medium text-gray-600 dark:text-gray-300">Status</th>
					<th class="px-4 py-3 text-right font-medium text-gray-600 dark:text-gray-300">Priority</th>
				</tr>
			</thead>
			<tbody>
				{#each edges as edge (edge.cursor)}
					<tr
						class="border-b border-gray-100 last:border-0 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800"
					>
						<td class="px-4 py-3 font-mono text-xs text-gray-500 dark:text-gray-400">
							{edge.node.id}
						</td>
						<td class="px-4 py-3 text-gray-900 dark:text-gray-100">
							{edge.node.title}
						</td>
						<td class="px-4 py-3">
							<span class="font-medium {statusClass(edge.node.status)}">
								{edge.node.status}
							</span>
						</td>
						<td class="px-4 py-3 text-right text-gray-600 dark:text-gray-300">
							{edge.node.priority}
						</td>
					</tr>
				{/each}
				{#if edges.length === 0}
					<tr>
						<td colspan="4" class="px-4 py-8 text-center text-gray-400 dark:text-gray-600">
							No beads found.
						</td>
					</tr>
				{/if}
			</tbody>
		</table>
	</div>

	{#if pageInfo.hasNextPage}
		<div class="flex justify-center">
			<button
				onclick={loadMore}
				disabled={loadingMore}
				class="rounded-md border border-gray-300 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-800"
			>
				{loadingMore ? 'Loading…' : 'Load more'}
			</button>
		</div>
	{/if}
</div>

// cli/internal/server/frontend/src/pages/Beads.tsx
import { useState } from 'react'
import { api } from '../api'
import { useFetch } from '../hooks/useFetch'
import type { Bead } from '../types'

const STATUS_COLORS: Record<string, string> = {
  open: 'bg-blue-100 text-blue-800 border-blue-200',
  in_progress: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  closed: 'bg-green-100 text-green-800 border-green-200',
}

const COLUMNS = ['open', 'in_progress', 'closed']

export default function Beads() {
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const beads = useFetch(() => api.beads(), [])

  const grouped: Record<string, Bead[]> = { open: [], in_progress: [], closed: [] }
  for (const b of (beads.data ?? []) as Bead[]) {
    const key = grouped[b.status] ? b.status : 'open'
    grouped[key].push(b)
  }

  return (
    <div className="flex h-full gap-4">
      <div className="flex-1 flex gap-3 overflow-auto">
        {COLUMNS.map((col) => (
          <div key={col} className="flex-1 min-w-[240px]">
            <h2 className="text-sm font-bold uppercase text-gray-500 mb-2">
              {col.replace('_', ' ')} ({grouped[col].length})
            </h2>
            <div className="space-y-2">
              {grouped[col].map((b) => (
                <button
                  key={b.id}
                  onClick={() => setSelectedId(b.id === selectedId ? null : b.id)}
                  className={`w-full text-left rounded-lg border p-3 text-sm shadow-sm ${
                    selectedId === b.id ? 'ring-2 ring-blue-400' : ''
                  } ${STATUS_COLORS[col] ?? 'bg-gray-50 border-gray-200'}`}
                >
                  <div className="font-medium">{b.title}</div>
                  <div className="text-xs mt-1 opacity-70">
                    {b.id} · P{b.priority}
                    {b.labels?.length ? ` · ${b.labels.join(', ')}` : ''}
                  </div>
                </button>
              ))}
              {grouped[col].length === 0 && (
                <div className="text-xs text-gray-400 p-2">None</div>
              )}
            </div>
          </div>
        ))}
      </div>
      {selectedId && (
        <div className="w-80 shrink-0">
          <BeadDetail id={selectedId} onClose={() => setSelectedId(null)} />
        </div>
      )}
    </div>
  )
}

function BeadDetail({ id, onClose }: { id: string; onClose: () => void }) {
  const bead = useFetch(() => api.beadDetail(id), [id])
  const depTree = useFetch(() => api.beadDepTree(id), [id])

  if (bead.loading) return <div className="text-gray-400 text-sm">Loading...</div>
  if (bead.error) return <div className="text-red-500 text-sm">Error: {bead.error}</div>

  const b = bead.data as Bead
  return (
    <div className="bg-white rounded-lg shadow border border-gray-200 p-4 text-sm space-y-3">
      <div className="flex justify-between items-start">
        <h3 className="font-bold">{b.title}</h3>
        <button onClick={onClose} className="text-gray-400 hover:text-gray-600">&times;</button>
      </div>
      <div className="text-xs text-gray-500">{b.id} · {b.status} · P{b.priority}</div>
      {b.labels?.length ? (
        <div className="flex gap-1 flex-wrap">
          {b.labels.map((l) => (
            <span key={l} className="bg-gray-100 px-2 py-0.5 rounded text-xs">{l}</span>
          ))}
        </div>
      ) : null}
      {b.description && (
        <div>
          <div className="font-medium text-gray-600 mb-1">Description</div>
          <p className="text-gray-700">{b.description}</p>
        </div>
      )}
      {b.acceptance && (
        <div>
          <div className="font-medium text-gray-600 mb-1">Acceptance</div>
          <p className="text-gray-700">{b.acceptance}</p>
        </div>
      )}
      {depTree.data?.tree && (
        <div>
          <div className="font-medium text-gray-600 mb-1">Dependencies</div>
          <pre className="text-xs bg-gray-50 rounded p-2 overflow-auto">{depTree.data.tree}</pre>
        </div>
      )}
    </div>
  )
}
