// cli/internal/server/frontend/src/routes/nodes/[nodeId]/projects/[projectId]/personas/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	let selectedId = $state<string | null>(null);
	let selected = $derived.by(() => {
		if (selectedId !== null) {
			const match = data.personas.find((p) => p.id === selectedId);
			if (match) return match;
		}
		return data.personas.length > 0 ? data.personas[0] : null;
	});

	function fmtDate(iso: string | null): string {
		if (!iso) return '—';
		return new Date(iso).toLocaleString();
	}
</script>

<div class="flex h-full gap-0">
	<!-- Left panel: persona list -->
	<div class="flex w-64 shrink-0 flex-col border-r border-gray-200 dark:border-gray-700">
		<div
			class="flex items-center justify-between border-b border-gray-200 px-4 py-3 dark:border-gray-700"
		>
			<h1 class="text-sm font-semibold dark:text-white">Personas</h1>
			<span class="text-xs text-gray-700 dark:text-gray-300">{data.personas.length}</span>
		</div>
		<div class="min-h-0 flex-1 overflow-y-auto">
			{#each data.personas as p (p.id)}
				<button
					onclick={() => (selectedId = p.id)}
					class="w-full border-b border-gray-100 px-4 py-3 text-left hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800 {selected?.id ===
					p.id
						? 'bg-blue-50 dark:bg-blue-900/20'
						: ''}"
				>
					<div class="text-sm font-medium text-gray-900 dark:text-gray-100">{p.name}</div>
					{#if p.roles.length > 0}
						<div class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">
							{p.roles.join(', ')}
						</div>
					{/if}
				</button>
			{/each}
			{#if data.personas.length === 0}
				<div class="px-4 py-8 text-center text-xs text-gray-700 dark:text-gray-300">
					No personas found.
				</div>
			{/if}
		</div>
	</div>

	<!-- Right panel: persona detail -->
	<div class="min-w-0 flex-1 overflow-y-auto p-6">
		{#if selected}
			<div class="space-y-4">
				<div>
					<h2 class="text-lg font-semibold dark:text-white">{selected.name}</h2>
					<p class="mt-1 text-sm text-gray-600 dark:text-gray-300">{selected.description}</p>
				</div>

				<!-- Metadata grid -->
				<div class="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
					{#if selected.roles.length > 0}
						<div>
							<div class="text-xs font-medium text-gray-500 dark:text-gray-400">Roles</div>
							<div class="mt-1 flex flex-wrap gap-1">
								{#each selected.roles as role}
									<span
										class="rounded bg-blue-100 px-1.5 py-0.5 text-xs text-blue-700 dark:bg-blue-900/40 dark:text-blue-300"
									>
										{role}
									</span>
								{/each}
							</div>
						</div>
					{/if}
					{#if selected.tags.length > 0}
						<div>
							<div class="text-xs font-medium text-gray-500 dark:text-gray-400">Tags</div>
							<div class="mt-1 flex flex-wrap gap-1">
								{#each selected.tags as tag}
									<span
										class="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-600 dark:bg-gray-700 dark:text-gray-300"
									>
										{tag}
									</span>
								{/each}
							</div>
						</div>
					{/if}
					<div>
						<div class="text-xs font-medium text-gray-500 dark:text-gray-400">Modified</div>
						<div class="mt-1 text-xs dark:text-gray-200">{fmtDate(selected.modTime)}</div>
					</div>
					{#if selected.filePath}
						<div class="col-span-2 sm:col-span-3">
							<div class="text-xs font-medium text-gray-500 dark:text-gray-400">File</div>
							<div class="mt-1 font-mono text-xs break-all text-gray-500 dark:text-gray-400">
								{selected.filePath}
							</div>
						</div>
					{/if}
					{#if selected.bindings.length > 0}
						<div class="col-span-2 sm:col-span-3">
							<div class="text-xs font-medium text-gray-500 dark:text-gray-400">Bindings</div>
							<div class="mt-1 flex flex-wrap gap-1">
								{#each selected.bindings as binding}
									<span
										class="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-600 dark:bg-gray-700 dark:text-gray-300"
									>
										{binding.projectId}: {binding.role}
									</span>
								{/each}
							</div>
						</div>
					{/if}
				</div>

				<!-- Content -->
				<div>
					<div class="mb-2 text-xs font-medium text-gray-500 dark:text-gray-400">
						Prompt / Instructions
					</div>
					<pre
						class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 font-mono text-xs leading-relaxed whitespace-pre-wrap text-gray-800 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200">{selected.body}</pre>
				</div>
			</div>
		{:else}
			<div class="flex h-full items-center justify-center text-gray-700 dark:text-gray-300">
				Select a persona to view details.
			</div>
		{/if}
	</div>
</div>

// cli/internal/server/frontend/src/pages/Personas.tsx
import { useState } from 'react'
import { useFetch } from '../hooks/useFetch'
import { api } from '../api'

interface PersonaSummary {
  name: string
  description: string
  roles: string[]
  tags: string[]
}

export default function Personas() {
  const { data: personas, loading } = useFetch<PersonaSummary[]>(() => api.personas())
  const [selected, setSelected] = useState<string | null>(null)
  const [content, setContent] = useState<string>('')
  const [loadingContent, setLoadingContent] = useState(false)

  const loadContent = async (name: string) => {
    setSelected(name)
    setLoadingContent(true)
    try {
      // Resolve persona content via the role endpoint (use first role or name)
      const persona = personas?.find(p => p.name === name)
      const role = persona?.roles?.[0] || name
      const data = await api.personaDetail(role)
      setContent(data.content || 'No content available')
    } catch {
      setContent('Could not load persona content')
    }
    setLoadingContent(false)
  }

  if (loading) return <div className="p-6 text-gray-500">Loading personas...</div>
  if (!personas?.length) return <div className="p-6 text-gray-500">No personas found</div>

  return (
    <div className="flex h-full">
      <div className="w-80 border-r overflow-y-auto p-4">
        <h2 className="text-lg font-bold mb-4">Personas</h2>
        {personas.map(p => (
          <button
            key={p.name}
            onClick={() => loadContent(p.name)}
            className={`w-full text-left p-3 rounded-lg mb-2 border transition ${
              selected === p.name
                ? 'border-blue-500 bg-blue-50'
                : 'border-gray-200 hover:border-gray-300'
            }`}
          >
            <div className="font-medium text-sm">{p.name}</div>
            {p.description && (
              <div className="text-xs text-gray-500 mt-1">{p.description}</div>
            )}
            {p.roles?.length > 0 && (
              <div className="flex gap-1 mt-2 flex-wrap">
                {p.roles.map(r => (
                  <span key={r} className="text-xs bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">
                    {r}
                  </span>
                ))}
              </div>
            )}
            {p.tags?.length > 0 && (
              <div className="flex gap-1 mt-1 flex-wrap">
                {p.tags.map(t => (
                  <span key={t} className="text-xs bg-gray-100 text-gray-600 px-1.5 py-0.5 rounded">
                    {t}
                  </span>
                ))}
              </div>
            )}
          </button>
        ))}
      </div>
      <div className="flex-1 overflow-y-auto p-6">
        {selected ? (
          loadingContent ? (
            <div className="text-gray-500">Loading...</div>
          ) : (
            <div>
              <h2 className="text-xl font-bold mb-4">{selected}</h2>
              <pre className="whitespace-pre-wrap text-sm bg-gray-50 border rounded-lg p-4 font-mono">
                {content}
              </pre>
            </div>
          )
        ) : (
          <div className="text-gray-400 text-center mt-20">
            Select a persona to view its content
          </div>
        )}
      </div>
    </div>
  )
}
